# Site settings
title: 晓龙
email: sky@itoytoy.com
description: >
  为儿女和自己而写。记录产品，时间管理，读书感想。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zxlive.github.io" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/zxl', 'fa-user']
single_footer: '<p>Copyright &copy; 2017 <a href="/">latest posts</a></p>'
footer_links:


# Build settings
# markdown: kramdown
